### ISSUE TITLE
Support emitting toml

### ISSUE THREAD

**Issue by zml2008** [mwanji/toml4j#16]
For configurations, it is common to load in a user's configuration and modify it -- through a user interface for the configuration, migrating to an updated schema, deleting unused values, or just cleaning up the input. To support this functionality in TOML, it would be helpful to be able to serialize a Toml object into a toml-format configuration.

Also important to many of my users (I maintain the [Configurate](https://github.com/zml2008/configurate) library which is gaining popularity within the Minecraft modding community) is the ability to roundtrip comments -> so when a user places a comment on a value in the configuration, that comment is read with the rest of the configuration data, can be set programatically, and will be emitted with the rest of the configuration on save.

**Comment by mwanji** [comment]
I agree that emitting TOML could be useful. I haven't put any work into that so far because I haven't needed it. I'll consider getting this in in time for the 1.0 release. Does Configurate currently support TOML? I see folders for other formats, but not TOML.

Currently comments aren't preserved, so it would take some reworking. So probably not for 1.0.

**Comment by zml2008** [comment]
I've got some initial toying around with toml locally, but I haven't pushed anything because there aren't any java toml libraries that provide the features we need.

I'd really like to get these features in, and would be willing to help out with implementation pieces (as others would be I'm sure) if you'd like.

**Comment by mwanji** [comment]
@dilecti has started work on emitting TOML, which you can follow on the writer branch. You can also comment on #20.
