### ISSUE TITLE
Suggestion: Add a way to iterate over key-value pairs

### ISSUE THREAD

**Issue by Zero3** [mwanji/toml4j#4]
Hi there

I would like to suggest adding a way to iterate over key-value pairs of a Toml object or alternatively exposing a map of these. It seems like all current methods require you to know the name of the key, which i unfortunately do not always know in my use case.

**Comment by d3xter** [comment]
One possible use-case would be this taken from cargo (and expanded a bit):

    [dependencies]
    foo = { type="git", url="http://github.com/.../...", tag = "v0.1"}
    bar = { type="crates.io" version = "v1.0" }

One way to do it could be:

    Iterator<Map.Entry<String,Object> iterator = toml.getIterator("dependencies")
    while(iterator.hasNext()) {
        Map.Entry<String,Object> dependency = iterator.next();
        Map<String, Object> parameters = dependency.getValue();
        if(parameters.get("type").toString().equals("git")) {
            //Read the other parameters
        } else if(....)


The only downside is, that the user has to cast/check the values inside the parameters by himself.
That could be resolved when a Toml instance is used inside instead of a plain Map<>

**Comment by mwanji** [comment]
Sorry @d3xter , I only just saw your comment. You and @Zero3 may be interested in PR https://github.com/mwanji/toml4j/pull/15

Tell me if you like the rewritten example it allows:

```java
Set<Toml.Entry> dependencies = toml.getTable("dependencies").entrySet();

for (Toml.Entry dependency : dependencies) {
  String dependencyName = dependency.getKey();
  Toml dependencyInfo = dependency.getValue();

  if ("git".equals(dependencyInfo.get("type")) {

  } // etc...
}
```

**Comment by Zero3** [comment]
The example looks good. Here is a suggestion for a slight simplification and a little more type safety:

    Set<Toml.Entry> dependencies = toml.getTable("dependencies").entrySet(); // Throws exception if "dependencies" is not a table
    
    for (Toml.Entry dependency : dependencies) 
    {
        String dependencyName = dependency.getKey());
        String dependencyType = dependency.getStringValue("type")); // Throws exception if the "type" entry is not a String.
        
        if ("git".equals(dependencyType))
        {
            // ...
        }
    }

**Comment by mwanji** [comment]
`toml.getTable("dependencies").entrySet(); // Throws exception if "dependencies" is not a table`

getTable() already [throws an exception](https://github.com/mwanji/toml4j/blob/439d1c600dafb0c973ae40b81e280f072c405a02/src/main/java/com/moandjiezana/toml/Toml.java#L215). entrySet() only exists on the Toml class.

`dependency.getStringValue("type")); // Throws exception if the "type" entry is not a String.`

In this situation, you're already "reflecting" on the TOML because you're not sure what it contains, so I don't think adding type safety features really makes sense. Plus, it would end up duplicating many of Toml's methods, for little gain. As Toml.Entry#getValue() can never return null, the type of its return value can be safely obtained with getClass().

I see this functionaliy being used mostly by frameworks, where typesafety is less important, as the framework needs to handle all kinds of cases, such as missing keys and invalid values, which isn't really made much easier with getStringValue()-style methods. If I'm proven wrong, then they can be added, but I don't think they're necessary right now.

**Comment by Zero3** [comment]
I think the main added benefit of adding a getStringValue() (and similar) would be that you get a String back, and not an Object. I realize that you can simply cast the Object to a String after obtaining it, though this looks somewhat more questionable in code in my opinion. I'd rather specify the type I intend to receive in the name of the method (and let the library assert that this is valid). I agree that this is a matter of weighting various factors such as convenience, keeping the number of methods in the API small, ... Either approach will work for me, I just have a slight preference for the typed versions.

My argument for the suggested "shortcut" methods in my example above, where you skip a lookup step by providing a String directly to the getStringValue() method, is somewhat the same: It would make my own code slightly simpler and easier to understand, making me a happier user of your library.

Either way, I trust your judgment, because the library is looking pretty good so far :).

**Comment by mwanji** [comment]
`(String) entry.getValue()` vs `entry.getStringValue()`

Considering that we'd probably then also add the overloaded versions that take a default value, adding a dozen methods to avoid a cast doesn't seem beneficial.

However, I suggest that you open this in a new issue so that it can be revived in the future. Maybe the library will evolve in a way that makes this feasible, someone will think up a better way or there will be enough demand.

**Comment by mwanji** [comment]
I've modified #15 so that it returns Map.Entry instances instead of Toml.Entry.

The advantage is that it reduces the number of custom types exposed to the user. In the future, this may also allow me to simplify how the entry set is created.

The downside is that Map.Entry#setValue() throws an UnsupportedOperationException. This is allowed by the Map.Entry contract and I don't think setValue() is used much.

**Comment by mwanji** [comment]
This has been merged into wip
